name: GeikRobot
main: com.geik.chat.Main
version: 1.0
author: Geik
api-version: 1.13
soft-depend: [TitleManager, Vault]
commands:
  temizle:
     description: temizle
  sustur:
     description: susturur